- .github/workflows/moodle-to-ghcr-on-push.yaml
Add necessary permission to build and push the image.
> Update moodle-to-ghcr-on-push.yaml (fix permissions)

- .github/workflows/moodle-to-ghcr-on-push.yaml
Changed ignored branch from master to main
> Update moodle-to-ghcr-on-push.yaml (fix ignore)

- moodleUpdateCheck.sh
Added the migration of plugin files from the old moodle to the new installed moodle version. Works as long as we are in the same stable version (4.1.x).
> Dbp 257 include plugins and themes in the automated moodle update process

- Dockerfile
- moodleUpdateCheck.sh
Updated the Docker Image script to use Moosh for automatic Plugin Updates after the Moodle Version Update.
Won't interfere with any Moodle Deployment because a new Moodle Image will need to be build for any changes to take place.
> Dbp 263 evaluate way to update moodle plugins automatically

- Dockerfile
Using new Moodle Image to Update to 4.1.6 because of a CVE
> Update Moodle Image Version

- Dockerfile
- moodleUpdateCheck.sh
Included Kaltura plugin installation if the ENV variable is set to true.
Error handling on wrong kaltura download url to receive correct error logs.
Fixed bug with wrong path: /volumes/moodledata/UpdatePlugins   (volumes -> bitnami)
> Dbp 217 anbindung d golive an moodle

- Dockerfile
- update base image to version 4.1.8
- former OPS-5664 ticket, moved it to the right context
> DBP-558-update-moodle-to-4.1.8

- moodleUpdateCheck.sh
- fix condition so that Kaltura is only installed and updated when the KALTURA_ENABLED Flag is set and True. At the moment the condition is true if the ENV exists no matter the value. 
> DBP-558-update-moodle-4.1.8

- Dockerfile
- moodleUpdateCheck.sh
- phpRedisInstall.sh
> Dbp 419 setup redis cluster

- Dockerfile
> Update bitnami moodle to 4.1.10-debian-12-r3

- .github/workflows/build-and-push-on-tag.yaml
> Added permissions

- .github/workflows/build-and-push-on-tag.yaml
- Dockerfile
> small change

- Dockerfile
- moodleUpdateCheck.sh
> Dbp-760-improvement-of-moosh-installation-in-the-moodle-image

- Dockerfile
> DBP-629-update_moodle_to_4.1.10

- .github/workflows/build-and-push-on-tag.yaml
- removed literal '.' (from GHA) which does not mean 'any character' as in usual regex and prevented gha runs for tags (GHA use [glob syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore), not regex)
- changed matching of suffix pattern
> Update Moodle to 4.1.10 (and fix GHA)

- moodleUpdateCheck.sh
> DBP-629 less than is wrong here, use equal isntead

- Dockerfile
- entrypoint.sh
- moodleUpdateCheck.sh
- general improvements
- split entrypoint and update skripts
- create persistent log file for update skript
[DBP-815](https://ticketsystem.dbildungscloud.de/browse/DBP-815)
> Dbp 815 improve moodle update debug

- moodleUpdateCheck.sh
> Fix Kalturi unzip path

- Dockerfile
- entrypoint.sh
- moodleUpdateCheck.sh
> Dbp 843 fix moodle update script

- Dockerfile
Create updated moodle image (4.1.11)
[OPS-6620](https://ticketsystem.dbildungscloud.de/browse/OPS-6620)
> OPS-6620-update-moodle-4.1.11

- charts/dbp-moodle/scripts/backup.sh
- charts/dbp-moodle/templates/roles/backup-role.yaml
- charts/dbp-moodle/templates/roles/moodle-cronjob-role.yaml
- charts/dbp-moodle/values.yaml
[fix some faulty variables, one indentation, one yaml formatting error](https://github.com/dBildungsplattform/dbp-moodle/commit/75324835b5cf3e02ea843065b1dd4ffeba604b46)
> fix some faulty variables, one indentation, one yaml formatting error

- charts/dbp-moodle/Chart.lock
- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/values.yaml
Add dependency for sql-exporter (increasing versiuon to current latest)
Migrate settings from infra-schulcloud repo
> DBP-899 moodle monitoring with sql-exporter

- charts/dbp-moodle/scripts/hook/moodle-update-preparation.sh
> Dbp 000 fix update hook with disabled backup

- Dockerfile
> Changed Image Version to 4.1.12

- charts/dbp-moodle/Chart.lock
- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/scripts/moodleRestoreScript.sh
- charts/dbp-moodle/templates/_helpers.tpl
- charts/dbp-moodle/templates/hpa.yaml
- charts/dbp-moodle/templates/jobs/moodle-restore-job.yaml
- charts/dbp-moodle/templates/secrets/moodle-backup-gpg-keys.yaml
- charts/dbp-moodle/templates/secrets/moodle-s3-secret.yaml
- charts/dbp-moodle/templates/serviceaccounts/moodle-update-preparation-hook-serviceaccount.yaml
- charts/dbp-moodle/values.yaml
> Dbp-951-chart-adaptions-for-usability

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/scripts/backup.sh
- charts/dbp-moodle/scripts/moodleRestoreScript.sh
- charts/dbp-moodle/values.yaml
> correct postgres user in restore script

- Dockerfile
- charts/dbp-moodle/README.md
- charts/dbp-moodle/templates/_helpers.tpl
- charts/dbp-moodle/templates/chart-hooks/moodle-update-preparation-job.yaml
- charts/dbp-moodle/templates/jobs/moodle-restore-job.yaml
- charts/dbp-moodle/templates/secrets/moodle-secret.yaml
- charts/dbp-moodle/values.yaml
- scripts/init/entrypoint.sh
Adjustment of the code to be kyverno rule conform in the RZ.
> Dbp 950 kyverno rules for moodle

- charts/dbp-moodle/scripts/backup.sh
- charts/dbp-moodle/scripts/moodleRestoreScript.sh
- charts/dbp-moodle/templates/configmaps/duply-configmap.yaml
- charts/dbp-moodle/templates/jobs/moodle-restore-job.yaml
- charts/dbp-moodle/values.yaml
> switch to cron tools image

- charts/dbp-moodle/scripts/config.php
helm secret lookup if existing secret is set, else password
> Dbp 000 - helm existingsecret lookup

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/templates/_helpers.tpl
- charts/dbp-moodle/values.yaml
- scripts/install/downloadPlugins.sh
> Dbp 000 add 3 plugins

- charts/dbp-moodle/scripts/config.php
- charts/dbp-moodle/templates/_helpers.tpl
- charts/dbp-moodle/values.yaml
- scripts/install/downloadPlugins.sh
> Dbp 000 - 3 new theme plugins

- charts/dbp-moodle/templates/chart-hooks/moodle-restore-job.yaml
- charts/dbp-moodle/templates/chart-hooks/moodle-update-preparation-job.yaml
- charts/dbp-moodle/templates/configmaps/moodle-restore-script-configmap.yaml
- charts/dbp-moodle/templates/rolebindings/restore-rolebinding.yaml
- charts/dbp-moodle/templates/roles/restore-role.yaml
- charts/dbp-moodle/templates/serviceaccounts/restore-serviceaccount.yaml
> Dbp-998-implement-restore-as-hook

- charts/dbp-moodle/templates/configmaps/moodle-sql-exporter-configmap.yaml
- charts/dbp-moodle/values.yaml
add sql-exporter metrics as configmap, discern between mariadb and postgresql queries and finally mount it to the right path
> DBP-000 Fix moodle sql exporter

- charts/dbp-moodle/scripts/moodleCronjobScript.sh
- charts/dbp-moodle/values.yaml
> Dbp-1001-moodle-cronjob-wait-for-moodle

- charts/dbp-moodle/scripts/moodleCronjobScript.sh
- charts/dbp-moodle/values.yaml
> Dbp-000-fix-backup-error-messages-from-kubernetes

- Dockerfile
> Update Moodle image to 4.1.13

- scripts/init/updateCheck.sh
Turns out this is not necessary for fresh install without internet access, but it still is faster by roughly a minute
> Unpack moodle from image on fresh install

- charts/dbp-moodle/values.yaml
- moodle/Dockerfile
> Ops 7063 update moodle to 4 1 14

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
Increased chart version for new release. 
> DBP-1035-dbp-moodle-0.0.7

- charts/dbp-moodle/README.md
- charts/dbp-moodle/values.yaml
The functionality for extra URLs is already there, just pretty hidden.
Refer to infra-03 NS for example
> Add default value for extraHosts with empty list and appropriate comment

- charts/dbp-moodle/scripts/hook/moodle-update-preparation.sh
- charts/dbp-moodle/templates/chart-hooks/moodle-update-preparation-job.yaml
> add readiness and liveness probe to updateCheck Job

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
- charts/dbp-moodle/templates/_helpers.tpl
- moodle/scripts/install/downloadPlugins.sh
falsely listed them as theme plugins when they are format plugins
> moodle 2 plugins fix

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
> Bump Chart version to 0.0.9

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
- charts/dbp-moodle/scripts/moodleRestoreScript.sh
- charts/dbp-moodle/templates/chart-hooks/moodle-restore-job.yaml
- charts/dbp-moodle/values.yaml
> Update restore Job

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
> bump chart version

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
- charts/dbp-moodle/scripts/backup.sh
- charts/dbp-moodle/values.yaml
> Dbp 000 nonroot cronjob

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
- charts/dbp-moodle/scripts/restore.sh
> use enabled value for custom secret

- moodle-tools/README.md
- moodle/README.md
> Dbp 1016 update moodle documentation

- moodle/Dockerfile
> OPS-7613-Update-Moodle-to-4.1.15

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
- charts/dbp-moodle/scripts/config.php
- charts/dbp-moodle/values.yaml
- moodle/Dockerfile
> Ops 7421 prevent moodle plugin UI installation

- .github/workflows/moodle-tools-bap-on-tag.yaml
> Ops-7465-add-suffix-to-moodle-tools-image

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
- charts/dbp-moodle/values.yaml
- moodle/Dockerfile
> DBP-1372 update moodle images 4.5.3

- moodle/Dockerfile
> DBP-1429-increasing moodle vers

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
- charts/dbp-moodle/values.yaml
> DBP-1249-increasing helm chart versions

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
- charts/dbp-moodle/values.yaml
> DBP-1429-setting usePasswordFiles to false

- charts/dbp-moodle/README.md
- charts/dbp-moodle/scripts/config.php
- charts/dbp-moodle/values.yaml
Added configuration to make blocking and allowing of IP addresses possible.
> Dbp 1388 create option for moodle ip blocker

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/scripts/backup.sh
- charts/dbp-moodle/scripts/restore.sh
- charts/dbp-moodle/templates/chart-hooks/moodle-restore-job.yaml
- charts/dbp-moodle/templates/configmaps/duply-configmap.yaml
- charts/dbp-moodle/values.yaml
- moodle-tools/Dockerfile
- moodle/scripts/init/entrypoint.sh
Includes all adjustments for the creation of moodle-tools-1.1.12 and dbp-moodle 0.0.33 to remove root privileges from the workflows.
> Dbp 1390 moodle image anpassungen

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
- charts/dbp-moodle/scripts/config.php
- charts/dbp-moodle/values.yaml
> Dbp 1456 increase moodle dependency versions

- charts/dbp-moodle/Chart.yaml
- charts/dbp-moodle/README.md
- charts/dbp-moodle/values.yaml
Switch all references to bitnami legacy
> DBP-1610-bitnami-legacy-migration
